# Generated by Django 4.2.5 on 2023-10-01 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('E', 'Education'), ('N', 'Networking'), ('H', 'Highlights')], default='E', max_length=1),
        ),
    ]
